server:
  port: 8088
eureka:
  instance:
    appname: peer01
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer02:8089/eureka/
    healthcheck:
      enabled: true
    #registerWithEureka: false
    #fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: true #设为false，关闭自我保护，从而保证会注销微服务
    eviction-interval-timer-in-ms: 4000 #清理间隔
