server:
  port: 8083
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
spring:
  application:
    name: dubbo-consumer
debug: false



