server:
  port: 8089
eureka:
  instance:
    appname: peer02
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer01:8088/eureka/
    healthcheck:
      enabled: true
    #registerWithEureka: false
    #fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0